version: 1.0.{build}
clone_folder: c:\mangos
environment:
build_script:
- go version
- go env
- SET PATH=%LOCALAPPDATA%\atom\bin;%PATH%
- go get -t ./...
- go build
- go install ./...
test_script:
- go test ./...
